services:
#    hs_listing.example:
#        class: HS\ListingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    hs_file_mover:
      class: HS\ListingBundle\Service\FileMover
      arguments: []

    hs_stat_calculator:
      class: HS\ListingBundle\Service\StatCalculator
      arguments: ["@doctrine.orm.entity_manager"]

    hs_pre_controller_execute:
        class: HS\ListingBundle\EventListener\ControllerEventSubscriber
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }