services:
#    hs_listing.example:
#        class: HS\ListingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    hs_file_mover:
      class: HS\ListingBundle\Service\FileMover
      arguments: []