hs_listing:
    resource: "@HSListingBundle/Controller/Listing/"
    type:     annotation
    prefix:   /

hs_order:
    resource: "@HSListingBundle/Controller/Order/"
    type:     annotation
    prefix:   /

hs_user:
    resource: "@HSUserBundle/Resources/config/routing.yml"
    prefix:   /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

