hs_listing:
    resource: "@HSListingBundle/Controller/"
    type:     annotation
    prefix:   /

hs_user:
    resource: "@HSUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
<<<<<<< HEAD


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
=======
>>>>>>> e289caf127a42e850e6c051092d2daa96e60081b
