<?php

namespace HS\ListingBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

	/**
	  * 
	  *	Returns all the categories created by the admin
	  *
	  *
	  * @return array of Categories
	  */
	public function getCategories()
	{
		return $this->findBy(array());

	}
}
