<?php

namespace HS\ListingBundle\Repository;

/**
 * ListingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingRepository extends \Doctrine\ORM\EntityRepository
{


	/**
	  * 
	  *	Returns all the listings created by the user passed as argument
	  *
	  * @param int $id The id of the actual user
	  *    
	  *
	  * @return array of Listing
	  */
	public function getUserListings($id)
	{
		return $this->findBy(array('user' => $id));
	}
	
}
