<?php

namespace HS\ListingBundle\Repository;

use HS\ListingBundle\Entity\ListingMetric;

/**
 * ListingMetricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingMetricRepository extends \Doctrine\ORM\EntityRepository
{

	public function addListingView($listing, $user)
	{
		$listingMetric =  $this->findOneBy(array("user" => $user->getId(), "listing" => $listing->getId()));

		if ($listingMetric == null) {
			$listingMetric = new ListingMetric();
			$listingMetric->setUser($user);
			$listingMetric->setListing($listing);
			$listingMetric->setViews($listingMetric->getViews() + 1);
			$this->getEntityManager()->persist($listingMetric);
		} else {
			$listingMetric->setViews($listingMetric->getViews() + 1);
		}

		$this->getEntityManager()->flush($listingMetric);

	}
}
