<?php

namespace HS\ListingBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use HS\ListingBundle\Entity\LOrder;

/**
 * LOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LOrderRepository extends ServiceEntityRepository
{


    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, LOrder::class);
    }


    public function addOrder($order)
    {
        $this->getEntityManager()->persist($order);
        $this->getEntityManager()->flush();
        return $order;
    }
}
